#!/bin/bash

read -p "Enter number : " n

for (( i=$n;i>0;i-- )) do
for (( j=1;j<i;j++ )) do
echo -n "$i "
done 
echo " "
done

for (( i=1;i<=$n;i++ )) do
for (( j=1;j<i;j++ )) do
echo -n "* "
done 
echo " "
done

for (( i=$n;i>=1;i-- )) do
for (( j=1;j<i;j++ )) do
echo -n " "
done 
for (( k=1;k<=($n-i+1);k++ )) do
echo -n "* "
done 
echo ""
done

for (( i=1;i<=$n;i++ )) do
for (( j=1;j<i;j++ )) do
echo -n "  "
done
for (( k=1;k<=($n-i+1);k++ )) do 
echo -n "* "
